version: 0.0

os: linux

files:
  - source: .
    destination: /home/ubuntu/trackwyse-backend-node

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
