#!/bin/bash

# Install the latest version of Node.js
sudo apt install nodejs -y

# Install the latest version of NPM
sudo apt install npm -y

# Install the latest version of Yarn
sudo npm install -g yarn

# Install the latest version of pm2
sudo npm install -g pm2

# Set node version to 16.14.0 on ubunt
sudo npm install -g n
sudo n 16.16.0